# Usando as variáveis de ambiente
spring.datasource.url=${DB_LA_URL}
spring.datasource.username=${DB_LA_USERNAME}
spring.datasource.password=${DB_LA_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configurações do JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true